version: '2.28.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toolconfigdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

services:
  toolconfiguration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toolconfiguration-container
    ports:
      - "8080:8080"
    image: toolconfiguration:latest
